### ISSUE TITLE
Fails to run if libc is not present

### ISSUE THREAD

**Issue by lpil** [stoeffel/elmi-to-json#21]
The elmi-to-json binary is not statically linked, and so it fails in environments missing libc (such as on alpine Linux, a popular linux distro when building docker images).

It'd be great to have this statically linked, or to have a musl version.

Relevant issue: https://github.com/rtfeldman/node-test-runner/issues/324

**Comment by stoeffel** [comment]
I don't think I'll get to this soon, sorry. But I would appreciate a PR.
