### ISSUE TITLE
Wasn't 0.19.2 published to npm?

### ISSUE THREAD

**Issue by andys8** [stoeffel/elmi-to-json#26]
It looks like the latest version wasn't published to npm. Was this a mistake or is it intended?

### NPM

![image](https://user-images.githubusercontent.com/13085980/57069397-d42b8800-6cd4-11e9-9632-4348264341b0.png)

### Releases
![image](https://user-images.githubusercontent.com/13085980/57069418-de4d8680-6cd4-11e9-95ee-82e7e3dc3ddf.png)

**Comment by stoeffel** [comment]
No that wasn't completely working. Will publish a new version asap.

**Comment by stoeffel** [comment]
@andys8 I just published 0.19.3.
