### ISSUE TITLE
No binaries are available for: darwin-arm64 (Mac OS Monterey with M1 chip)

### ISSUE THREAD

**Issue by rblnguyen** [stoeffel/elmi-to-json#45]
npm ERR! code 1
npm ERR! path /node_modules/elm-test/node_modules/elmi-to-json
npm ERR! command failed
npm ERR! command sh /var/folders/n5/j25h2kcn5qg5s2cnr_2091x40000gp/T/install-47a15f54.sh
npm ERR! /node_modules/elm-test/node_modules/binwrap/install.js:18
npm ERR!     throw new Error("No binaries are available for your platform: " + buildId);
npm ERR!     ^
npm ERR! 
npm ERR! Error: No binaries are available for your platform: darwin-arm64
npm ERR!     at install (/node_modules/elm-test/node_modules/binwrap/install.js:18:11)
npm ERR!     at Object.install (/node_modules/elm-test/node_modules/binwrap/index.js:14:14)
npm ERR!     at Object.<anonymous> (/node_modules/elm-test/node_modules/binwrap/bin/binwrap-install:18:9)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1126:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1004:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:17:47

**Comment by rblnguyen** [comment]
Any chance we can get some help with this? devs with M1 machine can't run elm tests. Not really want to switch out the test library for something else at the moment. Any help will be much appreciated. 

Look like there was a commit to add support for M1 on this commit but I have no idea why it's failing still
https://github.com/stoeffel/elmi-to-json/commit/774ead093cd64d83a9d029c7f3a3fa90e8962898

**Comment by avh4** [comment]
Which version are elm-test are you trying to install?  And what is your node/npm version?

**Comment by avh4** [comment]
Also I know there are folks who have elm-test working on M1.  If you want faster replies, you could also ask about this on the Elm Slack: https://elm-lang.org/community

**Comment by rblnguyen** [comment]
i thought i closed the issue. I found the solution for this. I was running "^0.19.1". 
look like switching to "elm-test": "^0.19.1-revision9" fixed the issue. I thought "^0.19.1" is sufficient but it's not.

Thank you Aaron.
